---
title: "2017-2021 NFL Scores"
author: "Kenizzer"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library('ggplot2')
library('ggpubr')
library('emmeans')
theme_set(theme_pubr())
```

## Add in data and print summary

This data set was generated by Reddit user **gigantoir** <https://www.reddit.com/r/NFLstatheads/comments/q73yd0/nfl_scores_20172020/>
I added the 2021 data that was scrapped from <https://www.footballdb.com/games/index.html>

```{r}
Scores <- read.csv("NFL_SCORES_2017-2021.txt", header=TRUE, sep= "\t")
Scores$Score_differential <- abs(Scores$Score_away - Scores$Score_home)
Scores$Week <- as.factor(Scores$Week)
summary(Scores)
```

```{r}
ggplot(Scores, aes(x=Week, y=Score_differential)) +
  geom_boxplot() +
  scale_x_discrete(breaks = seq(1,17,1), guide = guide_axis(n.dodge=2)) +
  facet_wrap(~Year)

ggplot(Scores, aes(x=Week, y=Score_differential)) +
  geom_smooth(aes(as.numeric(Week), Score_differential), method = "loess") +
  scale_x_continuous(breaks = seq(1,17,1), guide = guide_axis(n.dodge=2)) +
  facet_wrap(~Year)
```


```{r}
Score_varience <- c(var(Scores[Scores$Year == 2017, ]$Score_differential),
                    var(Scores[Scores$Year == 2018, ]$Score_differential),
                    var(Scores[Scores$Year == 2019, ]$Score_differential),
                    var(Scores[Scores$Year == 2020, ]$Score_differential),
                    var(Scores[Scores$Year == 2021, ]$Score_differential))
Score_varience <- as.data.frame(Score_varience)

Score_varience$Year <- c(2017,2018,2019,2020,2021)
Score_varience$Year <- as.factor(Score_varience$Year)


ggplot(Score_varience, aes(x=Year, y=Score_varience)) +
  geom_point(size = 3) +
  geom_line(aes(x=as.numeric(Year)))


```